const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const reportsRouter = require('./reportsRouter')
const reportsTableRouter = require('./reportsTableRouter')
const tableMilkShpRouter = require('./tableMilkShpRouter')
const tableMilkKfhRouter = require('./tableMilkKfhRouter')
const tableForageHarvestRouter = require('./tableForageHarvestRouter')
const tableCornSilageRouter = require('./tableCornSilageRouter')
const tableGsmRouter = require('./tableGsmRouter')
const tableAvalibleShTech = require('./tableAvalibleShTechRouter')
const tableReadyShTech = require('./tableReadyShTechRouter')
const tableBeetHarvesters = require('./tableBeetHarvestersRouter')
const tableHarvesters = require('./tableHarvestersRouter')
const tableLeftoverGrain = require('./tableLeftoverGrainRouter')
const tableTopDressing = require('./tableTopDressingRouter')
const tableCropCondition = require('./tableCropConditionRouter')
const tableFertilizerSpring = require('./tableFertilizerSpringRouter')
const tableFertilizerAutumn = require('./tableFertilizerAutumnRouter')
const tableHarrowing = require('./tableHarrowingRouter')
const tableSowSpringCrop = require('./tableSowSpringCropRouter')
const tableSowPotato = require('./tableSowPotatoRouter')
const tableSowVegetableAndGourd = require('./tableSowVegetableAndGourdRouter')
const tableSowPerennialPlanting = require('./tableSowPerennialPlantingRouter')
const tableFruitBerryHarvest = require('./tableFruitBerryHarvestRouter')
const tableVegetableHarvest = require('./tableVegetableHarvestRouter')
const tableSoilPreparation = require('./tableSoilPreparationRouter')
const tableSoyHarvest = require('./tableSoyHarvestRouter')
const tableSunflowerHarvest = require('./tableSunflowerHarvestRouter')
const tableBeetHarvest = require('./tableBeetHarvestRouter')
const tableSowWinterCrop = require('./tableSowWinterCropRouter')
const tableStaff = require('./tableStaffRouter')
const tableGrainForageBalance = require('./tableGrainForageBalanceRouter')

router.use('/user', userRouter)
router.use('/report', reportsRouter)
router.use('/reports_table', reportsTableRouter)
router.use('/milk_shp', tableMilkShpRouter)
router.use('/milk_kfh', tableMilkKfhRouter)
router.use('/forage_harvest', tableForageHarvestRouter)
router.use('/corn_silage', tableCornSilageRouter)
router.use('/gsm', tableGsmRouter)
router.use('/avalible_sh_tech', tableAvalibleShTech)
router.use('/ready_sh_tech', tableReadyShTech)
router.use('/beet_harvesters', tableBeetHarvesters)
router.use('/harvesters', tableHarvesters)
router.use('/leftover_grain', tableLeftoverGrain)
router.use('/top_dressing', tableTopDressing)
router.use('/crop_condition', tableCropCondition)
router.use('/fertilizer_spring', tableFertilizerSpring)
router.use('/fertilizer_autumn', tableFertilizerAutumn)
router.use('/harrowing', tableHarrowing)
router.use('/sow_spring_crop', tableSowSpringCrop)
router.use('/sow_potato', tableSowPotato)
router.use('/sow_vegetable_and_gourd', tableSowVegetableAndGourd)
router.use('/sow_perennial_planting', tableSowPerennialPlanting)
router.use('/fruit_berry_harvest', tableFruitBerryHarvest)
router.use('/vegetable_harvest', tableVegetableHarvest)
router.use('/soil_preparation', tableSoilPreparation)
router.use('/soy_harvest', tableSoyHarvest)
router.use('/sunflower_harvest', tableSunflowerHarvest)
router.use('/beet_harvest', tableBeetHarvest)
router.use('/sow_winter_crop', tableSowWinterCrop)
router.use('/staff', tableStaff)
router.use('/grain_forage_balance', tableGrainForageBalance)


module.exports = router