const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const reportsRouter = require('./reportsRouter')
const reportsTableRouter = require('./reportsTableRouter')
const tableMilkShpRouter = require('./tableMilkShpRouter')
const tableMilkKfhRouter = require('./tableMilkKfhRouter')
const tableForageHarvestRouter = require('./tableForageHarvestRouter')
const tableCornSilageRouter = require('./tableCornSilageRouter')
const tableGsmRouter = require('./tableGsmRouter')
const tableAvalibleShTech = require('./tableAvalibleShTechRouter')
const tableReadyShTech = require('./tableReadyShTechRouter')
const tableBeetHarvesters = require('./tableBeetHarvestersRouter')

router.use('/user', userRouter)
router.use('/report', reportsRouter)
router.use('/reports_table', reportsTableRouter)
router.use('/milk_shp', tableMilkShpRouter)
router.use('/milk_kfh', tableMilkKfhRouter)
router.use('/forage_harvest', tableForageHarvestRouter)
router.use('/corn_silage', tableCornSilageRouter)
router.use('/gsm', tableGsmRouter)
router.use('/avalible_sh_tech', tableAvalibleShTech)
router.use('/ready_sh_tech', tableReadyShTech)
router.use('/beet_harvesters', tableBeetHarvesters)

module.exports = router