const sequelize = require('../db')
const {DataTypes} = require('sequelize')

const User = sequelize.define('user', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    login: {type: DataTypes.STRING, unique: true},
    password: {type: DataTypes.STRING},
    role: {type: DataTypes.STRING, defaultValue: "USER"},
    region: {type: DataTypes.STRING}
})

const Reports = sequelize.define('reports', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    reports_name: {type: DataTypes.STRING, unique: true},
})

const ReportsTable = sequelize.define('reports_table', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    report_name: {type: DataTypes.STRING},
    table_name: {type: DataTypes.STRING, unique: true},
})

const TableMilkShp = sequelize.define('table_milk_shp', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result34: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    result56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    result48: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableMilkKfh = sequelize.define('table_milk_kfh', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result34: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableForageHarvest = sequelize.define('table_forage_harvest', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result34: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    result56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableCornSilage = sequelize.define('table_corn_silage', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableGsm = sequelize.define('table_gsm', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableAvalibleShTech = sequelize.define('table_avalible_sh_tech', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableReadyShTech = sequelize.define('table_ready_sh_tech', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableBeetHarvesters = sequelize.define('table_beet_harvesters', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
    value21: {type: DataTypes.FLOAT, defaultValue: "0"},
    value22: {type: DataTypes.FLOAT, defaultValue: "0"},
    value23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value24: {type: DataTypes.FLOAT, defaultValue: "0"},
    value25: {type: DataTypes.FLOAT, defaultValue: "0"},
    value26: {type: DataTypes.FLOAT, defaultValue: "0"},
    value27: {type: DataTypes.FLOAT, defaultValue: "0"},
    value28: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableHarvesters = sequelize.define('table_harvesters', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableLeftoverGrain = sequelize.define('table_leftover_grain', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
    value21: {type: DataTypes.FLOAT, defaultValue: "0"},
    value22: {type: DataTypes.FLOAT, defaultValue: "0"},
    value23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value24: {type: DataTypes.FLOAT, defaultValue: "0"},
    value25: {type: DataTypes.FLOAT, defaultValue: "0"},
    value26: {type: DataTypes.FLOAT, defaultValue: "0"},
    value27: {type: DataTypes.FLOAT, defaultValue: "0"},
    value28: {type: DataTypes.FLOAT, defaultValue: "0"},
    value29: {type: DataTypes.FLOAT, defaultValue: "0"},
    value30: {type: DataTypes.FLOAT, defaultValue: "0"},
    value31: {type: DataTypes.FLOAT, defaultValue: "0"},
    value32: {type: DataTypes.FLOAT, defaultValue: "0"},
    value33: {type: DataTypes.FLOAT, defaultValue: "0"},
    value34: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableTopDressing = sequelize.define('table_top_dressing', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result34: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    result56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableCropCondition = sequelize.define('table_crop_condition', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    result13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    result15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    result16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableFertilizerSpring = sequelize.define('table_fertilizer_spring', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result34: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    result67: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableFertilizerAutumn = sequelize.define('table_fertilizer_autumn', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableHarrowing = sequelize.define('table_harrowing', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result34: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    result56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSowSpringCrop = sequelize.define('table_sow_spring_crop', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    sum1: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    sum2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    result910: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1112: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1314: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1516: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1718: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1920: {type: DataTypes.FLOAT, defaultValue: "0"},
    value21: {type: DataTypes.FLOAT, defaultValue: "0"},
    value22: {type: DataTypes.FLOAT, defaultValue: "0"},
    result2122: {type: DataTypes.FLOAT, defaultValue: "0"},
    value23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value24: {type: DataTypes.FLOAT, defaultValue: "0"},
    result2324: {type: DataTypes.FLOAT, defaultValue: "0"},
    value25: {type: DataTypes.FLOAT, defaultValue: "0"},
    value26: {type: DataTypes.FLOAT, defaultValue: "0"},
    value27: {type: DataTypes.FLOAT, defaultValue: "0"},
    value28: {type: DataTypes.FLOAT, defaultValue: "0"},
    value29: {type: DataTypes.FLOAT, defaultValue: "0"},
    value30: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSowPotato = sequelize.define('table_sow_potato', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    result56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSowVegetableAndGourd = sequelize.define('table_sow_vegetable_and_gourd', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSowPerennialPlanting = sequelize.define('table_perennial_planting', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableFruitBerryHarvest = sequelize.define('table_fruit_berry_harvest', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
    value21: {type: DataTypes.FLOAT, defaultValue: "0"},
    value22: {type: DataTypes.FLOAT, defaultValue: "0"},
    value23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value24: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableVegetableHarvest = sequelize.define('table_vegetable_harvest', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
    value21: {type: DataTypes.FLOAT, defaultValue: "0"},
    value22: {type: DataTypes.FLOAT, defaultValue: "0"},
    value23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value24: {type: DataTypes.FLOAT, defaultValue: "0"},
    value25: {type: DataTypes.FLOAT, defaultValue: "0"},
    value26: {type: DataTypes.FLOAT, defaultValue: "0"},
    value27: {type: DataTypes.FLOAT, defaultValue: "0"},
    value28: {type: DataTypes.FLOAT, defaultValue: "0"},
    value29: {type: DataTypes.FLOAT, defaultValue: "0"},
    value30: {type: DataTypes.FLOAT, defaultValue: "0"},
    value31: {type: DataTypes.FLOAT, defaultValue: "0"},
    value32: {type: DataTypes.FLOAT, defaultValue: "0"},
    value33: {type: DataTypes.FLOAT, defaultValue: "0"},
    value34: {type: DataTypes.FLOAT, defaultValue: "0"},
    value35: {type: DataTypes.FLOAT, defaultValue: "0"},
    value36: {type: DataTypes.FLOAT, defaultValue: "0"},
    value37: {type: DataTypes.FLOAT, defaultValue: "0"},
    value38: {type: DataTypes.FLOAT, defaultValue: "0"},
    value39: {type: DataTypes.FLOAT, defaultValue: "0"},
    value40: {type: DataTypes.FLOAT, defaultValue: "0"},
    value41: {type: DataTypes.FLOAT, defaultValue: "0"},
    value42: {type: DataTypes.FLOAT, defaultValue: "0"},
    value43: {type: DataTypes.FLOAT, defaultValue: "0"},
    value44: {type: DataTypes.FLOAT, defaultValue: "0"},
    value45: {type: DataTypes.FLOAT, defaultValue: "0"},
    value46: {type: DataTypes.FLOAT, defaultValue: "0"},
    value47: {type: DataTypes.FLOAT, defaultValue: "0"},
    value48: {type: DataTypes.FLOAT, defaultValue: "0"},
    value49: {type: DataTypes.FLOAT, defaultValue: "0"},
    value50: {type: DataTypes.FLOAT, defaultValue: "0"},
    value51: {type: DataTypes.FLOAT, defaultValue: "0"},
    value52: {type: DataTypes.FLOAT, defaultValue: "0"},
    value53: {type: DataTypes.FLOAT, defaultValue: "0"},
    value54: {type: DataTypes.FLOAT, defaultValue: "0"},
    value55: {type: DataTypes.FLOAT, defaultValue: "0"},
    value56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value57: {type: DataTypes.FLOAT, defaultValue: "0"},
    value58: {type: DataTypes.FLOAT, defaultValue: "0"},
    value59: {type: DataTypes.FLOAT, defaultValue: "0"},
    value60: {type: DataTypes.FLOAT, defaultValue: "0"},
    value61: {type: DataTypes.FLOAT, defaultValue: "0"},
    value62: {type: DataTypes.FLOAT, defaultValue: "0"},
    value63: {type: DataTypes.FLOAT, defaultValue: "0"},
    value64: {type: DataTypes.FLOAT, defaultValue: "0"},
    value65: {type: DataTypes.FLOAT, defaultValue: "0"},
    value66: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSoilPreparation = sequelize.define('table_soil_preparation', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSoyHarvest = sequelize.define('table_soy_harvest', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    result56: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    result89: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1112: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1415: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    result1718: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
    value20: {type: DataTypes.FLOAT, defaultValue: "0"},
    result2021: {type: DataTypes.FLOAT, defaultValue: "0"},
    value21: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSunflowerHarvest = sequelize.define('table_sunflower_harvest', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    result23: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableBeetHarvest = sequelize.define('table_beet_harvest', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    result24: {type: DataTypes.FLOAT, defaultValue: "0"},
    result25: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableSowWinterCrop = sequelize.define('table_sow_winter_crop', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableStaff = sequelize.define('table_staff', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
})

const TableGrainForageBalance = sequelize.define('table_grain_forage_balance', {
    row_id: {type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true},
    row_owner: {type: DataTypes.STRING, defaultValue: "autoCreated"},
    date: {type: DataTypes.STRING, require: true},
    culture: {type: DataTypes.STRING, require: true},
    category: {type: DataTypes.STRING, require: true},
    value1: {type: DataTypes.FLOAT, defaultValue: "0"},
    value2: {type: DataTypes.FLOAT, defaultValue: "0"},
    result12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value3: {type: DataTypes.FLOAT, defaultValue: "0"},
    value4: {type: DataTypes.FLOAT, defaultValue: "0"},
    result45: {type: DataTypes.FLOAT, defaultValue: "0"},
    result46: {type: DataTypes.FLOAT, defaultValue: "0"},
    value5: {type: DataTypes.FLOAT, defaultValue: "0"},
    value6: {type: DataTypes.FLOAT, defaultValue: "0"},
    value7: {type: DataTypes.FLOAT, defaultValue: "0"},
    value8: {type: DataTypes.FLOAT, defaultValue: "0"},
    value9: {type: DataTypes.FLOAT, defaultValue: "0"},
    value10: {type: DataTypes.FLOAT, defaultValue: "0"},
    value11: {type: DataTypes.FLOAT, defaultValue: "0"},
    value12: {type: DataTypes.FLOAT, defaultValue: "0"},
    value13: {type: DataTypes.FLOAT, defaultValue: "0"},
    value14: {type: DataTypes.FLOAT, defaultValue: "0"},
    value15: {type: DataTypes.FLOAT, defaultValue: "0"},
    value16: {type: DataTypes.FLOAT, defaultValue: "0"},
    value17: {type: DataTypes.FLOAT, defaultValue: "0"},
    value18: {type: DataTypes.FLOAT, defaultValue: "0"},
    value19: {type: DataTypes.FLOAT, defaultValue: "0"},
})

User.hasOne(Reports)
Reports.belongsTo(User)

Reports.hasMany(ReportsTable)
ReportsTable.belongsTo(Reports)

module.exports = {
    User,
    Reports,
    ReportsTable,
    TableMilkShp,
    TableMilkKfh,
    TableCornSilage,
    TableForageHarvest,
    TableGsm,
    TableAvalibleShTech,
    TableReadyShTech,
    TableBeetHarvesters,
    TableHarvesters,
    TableLeftoverGrain,
    TableTopDressing,
    TableCropCondition,
    TableFertilizerSpring,
    TableFertilizerAutumn,
    TableHarrowing,
    TableSowSpringCrop,
    TableSowPotato,
    TableSowVegetableAndGourd,
    TableSowPerennialPlanting,
    TableFruitBerryHarvest,
    TableVegetableHarvest,
    TableSoilPreparation,
    TableSoyHarvest,
    TableSunflowerHarvest,
    TableBeetHarvest,
    TableSowWinterCrop,
    TableStaff,
    TableGrainForageBalance,
}